version: 0.2

phases:
    install:
     runtime-versions:
       dotnet: 6.0
     commands:
       - sudo apt-get update
       - sudo apt-get install -y dotnet-sdk-6.0
    pre_build:
     commands:
       - echo set selenium grid with chrome browser...
       - echo Logging in to AWS ECR...
       - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 132445211002.dkr.ecr.eu-west-2.amazonaws.com
       - echo set selenium grid with chrome browser...
       - docker pull selenium/standalone-chrome:4.1.3-20220405
       - docker network create automation_network || true
       - docker run -d -p 4444:4444 --shm-size="2g" --network automation_network --name seleniumgrid --network-alias seleniumgrid selenium/standalone-chrome:latest  
    build:
     commands:
       - echo Build started on `date`
       - echo Building the Docker image...
       - docker build -t 132445211002.dkr.ecr.eu-west-2.amazonaws.com/finalrepository:latest ./SeleniumSpecflowFrameworkfinal
       - docker images
       - docker run --env HOST_NAME=seleniumgrid --network automation_network --name DanielTest --volume "$(pwd)"/SeleniumSpecflowFrameworkfinal:/app/SeleniumSpecflowFrameworkfinal 132445211002.dkr.ecr.eu-west-2.amazonaws.com/finalrepository:latest
       - docker ps -a
       - ls -lrt
       - docker ps -a
       - ls -lrt
       - ls -lrt SeleniumSpecflowFrameworkfinal
       - docker ps -a
       - echo Logging in to AWS ECR...
       - echo Pushing the Docker image to AWS ECR...
       - docker push 132445211002.dkr.ecr.eu-west-2.amazonaws.com/finalrepository:latest 
     
   
   
  
