version: 0.2

phases:
    install:
     runtime-versions:
       dotnet: 6.0
     commands:
       - sudo apt-get update
       - sudo apt-get install -y dotnet-sdk-6.0
    pre_build:
     commands:
       - echo set selenium grid with chrome browser...
       -  echo Logging in to AWS ECR...
       - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 132445211002.dkr.ecr.eu-west-2.amazonaws.com     
    build:
     commands:
       - echo Build started on `date`
       - echo Building the Docker image...
       - docker build -t 132445211002.dkr.ecr.eu-west-2.amazonaws.com/finalrepository:latest ./SeleniumSpecflowFrameworkfinal
       - docker ps -a
       - echo Logging in to AWS ECR...
       - echo Pushing the Docker image to AWS ECR...
       - docker ps -a
       - docker push 132445211002.dkr.ecr.eu-west-2.amazonaws.com/finalrepository:latest 
   
   
  
