version: 0.2

phases:
    install:
     runtime-versions:
      dotnet: 6.0
    pre_build:
     commands:
       - echo set selenium grid with chrome browser...
       - docker pull selenium/standalone-chrome:4.1.3-20220405
       - docker network create automation_network || true
       - docker run -d -p 4444:4444 --shm-size="2g" --network automation_network --name seleniumgrid --network-alias seleniumgrid selenium/standalone-chrome:4.1.3-20220405    
    build:
     commands:
       - echo Build started on `date`
       - echo Building the Docker image...
       - docker build -t  practicefinal:latest .
       - docker ps -a
       - echo Build started on `date`
       - pwd
       - echo path "$(pwd)"mypath
       - docker create --env HOST_NAME=seleniumgrid --network automation_network --name SeleniumSpecflow_Frameworkfinal --volume "$(pwd)"/practicefinal/SeleniumSpecflowFrameworkfinal:/app/SeleniumSpecflowFrameworkfinal practicefinal:latest
       - docker ps -a
       - echo Build completed on `date`
       - ls -lrt
       - ls -lrt ./SeleniumSpecflowFrameworkfinal/
       - docker start -a SeleniumSpecflow_Frameworkfinal
       - echo Test Run Completed
       - echo Logging in to AWS ECR...
       - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 132445211002.dkr.ecr.eu-west-2.amazonaws.com
       - echo Pushing the Docker image to AWS ECR...
       - docker push 132445211002.dkr.ecr.eu-west-2.amazonaws.com/automationtest:latest 
   
   
  
