version: 0.2

phases:
  build:
    commands:
       - echo Building the Docker image...
       - docker build --rm=false -t 132445211002.dkr.ecr.eu-west-2.amazonaws.com/automationtest:latest SeleniumSpecflowFrameworkfinal
       - echo Logging in to AWS ECR...
       - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 132445211002.dkr.ecr.eu-west-2.amazonaws.com
       - echo Pushing the Docker image to AWS ECR...
       - docker push 132445211002.dkr.ecr.eu-west-2.amazonaws.com/automationtest:latest     
  
